# Generated by Django 5.0.6 on 2024-05-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('doctor_id', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
